### ISSUE TITLE
Change default port to avoid conflict with gateway

### ISSUE THREAD

**Issue by lidel** [ipfs/someguy#47]
Adding `SOMEGUY_PORT in https://github.com/ipfs/someguy/pull/45 is a good opportunity to change the default port to avoid conflict with gateway or any other tool that uses 8080 as default.

cc @hacdias @2color I imagine someone may want to try to run kubo (5001, 8080), rainbow (8090 & 8091), and someguy on the same machine. Right now their first experience would be to hit annoying "port taken" error, and having to read docs how to change it even before they can do anything.

Let's change someguy's default port from 8080 to something like 8142 (picked by a totally random dice).

Looks fairly boring and unused, and being in 8XXX range hints at it being HTTP service:
- https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
- https://www.speedguide.net/port.php?port=8142

**Comment by hacdias** [comment]
@lidel sounds like a plan to me, but may I suggest 8092? 😆 then we're inline with the others. Or is that too confusing?

**Comment by lidel** [comment]
8092 works too, unlikely for rainbow to expose another port any time soon. Maybe 8093 just to be safe, and the gap indicates separate service? ;-)

**Comment by lidel** [comment]
Noticed that `SOMEGUY_PORT` allows customizing port, while rainbow has `RAINBOW_GATEWAY_LISTEN_ADDRESS=127.0.0.1:8090`  which allows setting it to `0.0.0.0:8090` to listen on all interfaces. 

Perhaps we should unify and make someguy also have `SOMEGUY_LISTEN_ADDRESS` instead of just port?
