### ISSUE TITLE
HTTP 500 on no results

### ISSUE THREAD

**Issue by lidel** [ipfs/someguy#58]
### Problem

When requesting non-streaming response type (`application/json`),
/routing/v1/peers returns HTTP 500 instead of 404.

This in turn makes our infra swap payload into `text/html` error response.

Example:
- https://delegated-ipfs.dev/routing/v1/peers/12D3KooWDNdNqoDLGJbUAthEidnERkoyoGVHBejhcme6nH9ZedHY
- https://delegated-ipfs.dev/routing/v1/peers/12D3KooWDNdNqoDLGJbUAthEidnERkoyoGVHBejhcme6nH9ZedHZ :point_left: this will always fail, someguy returns HTTP 500.

### Solution

According to current specs, we should return HTTP 404:
Ref. https://specs.ipfs.tech/routing/http-routing-v1/#response-status-codes-0

Assuming a bug?

**Comment by hacdias** [comment]
This is a bug... in Boxo. I will take care of it.

**Comment by hacdias** [comment]
@lidel https://github.com/ipfs/boxo/pull/601
